routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::group(
    [
        'prefix'     => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect']
    ],
    function () {
        Route::get('/', ['as' => 'home', 'uses' => 'SiteController@index']);

        // Authentification
        /*Route::get(
            'auth/debug',
            [
                'as'   => 'login_debug',
                'uses' => 'AuthController@loginDebug'
            ]
        );*/

        // User
        Route::get(
            'user/profile',
            [
                'as'   => 'profile',
                'uses' => 'UserController@showProfile'
            ]
        );
        /*Route::get(
            'user/contacts',
            [
                'as'   => 'contacts',
                'uses' => 'UserController@showContacts'
            ]
        );
        Route::post(
            'user/contact/id',
            [
                'as'   => 'contacts-id',
                'uses' => 'UserController@ajaxGetContactsId'
            ]
        );
        Route::post(
            'user/contact',
            [
                'as'   => 'add-contact-twino',
                'uses' => 'UserController@ajaxAddContactUser'
            ]
        );*/

        //Site(s) / Game(s)
        Route::get(
            'game/{id}',
            [
                'as'   => 'show-stats',
                'uses' => 'SiteController@showStats'
            ]
        );
    }
);

Route::post(
    'user/updating',
    [
        'as'   => 'user-job-data-check',
        'uses' => 'UserController@ajaxCheckDataJob'
    ]
);
Route::get(
    'auth/login',
    [
        'as'   => 'login',
        'uses' => 'AuthController@redirectToProvider'
    ]
);
Route::get(
    'auth/logout',
    [
        'as'   => 'logout',
        'uses' => 'AuthController@logout'
    ]
);
Route::get(
    'auth/callback',
    [
        'as'   => 'twinoid-callback',
        'uses' => 'AuthController@handleProviderCallback'
    ]
);
Route::group(
    [
        'middleware' => ['permission:edit-category','ajax']
    ],
    function () {
        Route::resource(
            'category',
            'CategoryController',
            ['only' => ['create', 'store', 'edit', 'update']]
        );
        Route::resource(
            'stat',
            'StatController',
            ['only' => ['edit', 'update']]
        );
    }
);

app/Models/Site.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Config;

/**
 * App\Models\Site
 *
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Stat[] $stats
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Achievement[] $achievements
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\User[] $users
 */
class Site extends Model
{
    public $incrementing = false;
    protected $guarded = array('created_at', 'updated_at');

    public function stats()
    {
        return $this->hasMany('App\Models\Stat')->with('translations', 'category');
    }

    public function achievements()
    {
        return $this->hasMany('App\Models\Achievement')->with('translations');
    }

    public function users()
    {
        return $this->belongsToMany('App\Models\User')->withPivot('npoints');
    }

    public function categories()
    {
        return $this->hasMany('App\Models\Category');
    }
    public function getCategoriesStatsAttribute()
    {
        return $this->stats->pluck('category')->unique()->sortBy('name');
    }

    public function getProgressionGeneraleAttribute()
    {
        return round($this->pointsMax / \Config::get('twinoid.points_max') * 100);
    }

    public function pointsMax()
    {
        return $this->achievements()
                    ->selectRaw('site_id, SUM(npoints) as max')
                    ->groupBy('site_id');
    }

    public function getPointsMaxAttribute()
    {
        // if relation is not loaded already, let's do it first
        if (!$this->relationLoaded('pointsMax')) {
            $this->load('pointsMax');
        }
        $related = $this->getRelation('pointsMax')->first();
        // then return the count directly
        return ($related) ? (int)round($related->max, 5) : 0;
    }

    public function usersCount()
    {
        return $this->users()
                    ->selectRaw('site_id, count(*) as aggregate')
                    ->groupBy('site_id');
    }

    public function getUsersCountAttribute()
    {
        // if relation is not loaded already, let's do it first
        if (!$this->relationLoaded('usersCount')) {
            $this->load('usersCount');
        }
        $related = $this->getRelation('usersCount')->first();
        // then return the count directly
        return ($related) ? (int)$related->aggregate : 0;
    }

    public function statsCount()
    {
        return $this->stats()
                    ->selectRaw('site_id, count(*) as aggregate')
                    ->groupBy('site_id');
    }

    public function getStatsCountAttribute()
    {
        // if relation is not loaded already, let's do it first
        if (!$this->relationLoaded('statsCount')) {
            $this->load('statsCount');
        }
        $related = $this->getRelation('statsCount')->first();
        // then return the count directly
        return ($related) ? (int)$related->aggregate : 0;
    }

    public function achievementsCount()
    {
        return $this->achievements()
                    ->selectRaw('site_id, count(*) as aggregate')
                    ->groupBy('site_id');
    }

    public function getAchievementsCountAttribute()
    {
        // if relation is not loaded already, let's do it first
        if (!$this->relationLoaded('achievementsCount')) {
            $this->load('achievementsCount');
        }
        $related = $this->getRelation('achievementsCount')->first();
        // then return the count directly
        return ($related) ? (int)$related->aggregate : 0;
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Zizaco\Entrust\Traits\EntrustUserTrait;
use Acoustep\EntrustGui\Contracts\HashMethodInterface;
/**
 * App\Models\User
 *
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Site[] $sites
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Stat[] $stats
 */
class User extends BaseModel implements AuthenticatableContract, AuthorizableContract, HashMethodInterface
{
    use Authenticatable, EntrustUserTrait;

    protected $fillable = ['name'];

    public $incrementing = false;

    public function sites()
    {
        return $this->belongsToMany('App\Models\Site');
    }

    public function stats()
    {
        return $this->belongsToMany('App\Models\Stat');
    }
    public function statsSite()
    {
        return $this->stats()
                        ->where('site_id', $this->pivot->site_id);
    }
    public function achievementsSite()
    {
        return $this->achievements()
                    ->where('site_id', $this->pivot->site_id);
    }

    public function achievements()
    {
        return $this->belongsToMany('App\Models\Achievement');
    }
    public function getPointsAttribute()
    {
        return (int)$this->pivot->npoints;
    }
    public function getProgressionAttribute()
    {
        return round($this->pivot->npoints / \Config::get('twinoid.points_max') * 100);
    }
    //non utilisé - utile uniquement pour que le package entrust-gui fonctionne système
    public function entrustPasswordHash()
    {
    }
}

app/Http/Controllers/SiteController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Repositories\SiteRepository;
use Auth;

class SiteController extends Controller
{
    /**
     * @var \App\Repositories\SiteRepository
     */
    private $sites;

    public function __construct(SiteRepository $sites)
    {
        $this->sites = $sites;
    }

    public function index()
    {
        $user_id = 0;
        if (Auth::check()) {
            $user_id = Auth::user()->id;
        }
        return view('site.list', ['sites' => $this->sites->getAll($user_id)]);
    }

    public function showStats($id)
    {
        $id      = (int)$id;
        $user_id = 0;
        if (Auth::check()) {
            $user_id = Auth::user()->id;
        }
        $site = $this->sites->getById($id, $user_id);
//
//            $user      = Auth::user();
//            $user_site = $user->sites()->with('stats')->findOrFail($id);
//            foreach ($user_site->stats as $stat) {
////                $site->stats->find($stat->id)->score = $stat->score;
////                Debugbar::info($site->stats->find($stat->id)->score);
//                Debugbar::info($stat);
//            }
//        }
        return view('site.single', ['site' => $site]);
    }
}

resources/views/site/list.blade.php
@extends('layouts.app')

@section('title', 'Jeux')

@section('content')

    <?php
    $locales = Config::get('app.locales');
    ?>
    <ul class="nav nav-pills sites-lang-selector">
        <li><a href="" data-lang="" class="select-sites-by-lang">{{ ucfirst(trans('messages.tous_les_jeux')) }}</a></li>
        @foreach($locales as $code => $locale)
            <li><a href="" class="select-sites-by-lang" data-lang="{{ $code }}">{{ $locale['title'] }}</a></li>
        @endforeach
    </ul>
    <div class="row grid-sites">
        @foreach ($sites as $site)
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 box-site"
                 data-lang="{{ $site->lang ? $site->lang : 'all' }}">
                <div class="box box-solid">
                    @if($site->lang)
                        <i {!! Html::attributes(['class'=>'flag flag-'.$site->lang]) !!}></i>
                    @endif
                    <?php $user = $user_stats = $user_achievements = null?>
                    @if(!$site->users->isEmpty())
                        <?php $user = $site->users->first();
                        $user_stats = $user->statsSite();
                        $user_achievements = $user->achievementsSite();
                        ?>
                    @endif
                    <div class="box-body">
                        <div class="row">
                            <div class="col-xs-4 img-jeu">
                                {!! Html::image($site->cover, $site->name,['class' => 'img-responsive', 'width'=>135, 'height' => 157]) !!}
                            </div>
                            <div class="col-xs-8 stats">
                                <h2 class="text-center box-title">{{$site->name}}</h2>
                                <ul class="list-unstyled">
                                    <?php $nb_stats = $site->statsCount; ?>
                                    <?php $nb_achievements = $site->achievementsCount; ?>
                                    <?php $nb_points = $site->pointsMax;?>
                                    <?php $nb_joueurs = $site->usersCount; ?>
                                    <li>{!! $user_stats ? '<span>'.$user_stats->count().'</span> / ' :'' !!}@choice('messages.nb_stats', $nb_stats, ['nb' => '<span>'.$nb_stats.'</span>'])</li>
                                    <li>{!! $user_achievements ? '<span>'.$user_achievements->count().'</span> / ' :'' !!}@choice('messages.nb_recompenses', $nb_achievements, ['nb' => '<span>'.$nb_achievements.'</span>'])</li>
                                    <li>{!! $user ? '<span>'.$user->points.'</span> / ' :'' !!}@choice('messages.nb_points', $nb_points, ['nb' => '<span>'.$nb_points.'</span>'])</li>
                                    <li>@choice('messages.nb_joueurs', $nb_joueurs, ['nb' => '<span>'.$nb_joueurs.'</span>'])</li>
                                </ul>
                            </div>
                            <div class="col-xs-12 footer">
                                <div class="progress sm">
                                    <?php
                                    $progressionGeneraleWidth = $site->progressionGenerale;
                                    ?>
                                    @if($user)
                                        <?php $progressionJoueur = $user->progression ?>
                                        <div class="progress-bar progress-bar-aqua"
                                             style="width:{{ $user->progression }}%;">
                                        </div>
                                        <?php $progressionGeneraleWidth -= $progressionJoueur; ?>
                                    @endif
                                    <div class="progress-bar general-progress"
                                         style="width: {{$progressionGeneraleWidth}}%;">
                                    </div>
                                </div>
                                <div class="buttons text-center">
                                    <a href="{{route('show-stats',['id' => $site->id])}}"
                                       class="btn btn-block btn-primary" type="button">@lang('messages.pictos')</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
        <div class="col-xs-1 shuffle__sizer"></div>
    </div>
@endsection

resources/views/site/single-sidebar-menu.blade.php
<li class="header">{{ucfirst(trans('messages.categories'))}}</li>
<li class="active">
    <a href="" class="category-filter" data-group="all">
        <span>{{ucfirst(trans('messages.toutes-categories'))}}</span>
    </a>
</li>
<?php
$categories = $site->categories->sortBy('name');
?>
@foreach( $categories as $cat)
    <?php
    $has_children = $cat->children->count() > 0;
    ?>
    <li class="{{$has_children ? 'treeview' : ''}}">
        <a href="#" class="category-filter"
           data-group="{{ str_slug($cat->name).'-'.$cat->id }}">
            @if($cat->icon)
                {!! Html::image($cat->icon, $cat->name) !!}
            @endif
            <span>{{ $cat->name }}</span>
            @permission('edit-category')
            <i class="fa fa-fw fa-pencil btn-edit-category"
               data-href="{{ route('category.edit', ['category' => $cat->id]) }}"></i>
            @endpermission
            @if($has_children)
                <i class="fa fa-angle-left pull-right"></i>
            @endif
        </a>
        @if($has_children)
            <?php $children = $cat->children->sortBy('name'); ?>
            <ul class="treeview-menu">
                @foreach($children as $child)
                    <li>
                        <a href="#" class="category-filter child" data-group="{{ str_slug($child->name).'-'.$child->id }}">
                            @if($child->icon)
                                {!! Html::image($child->icon, $child->name) !!}
                            @endif
                            <span>{{ $child->name }}</span>
                            @permission('edit-category')
                            <i class="fa fa-fw fa-pencil btn-edit-category"
                               data-href="{{ route('category.edit', ['category' => $child->id]) }}"></i>
                            @endpermission
                        </a>
                    </li>
                @endforeach
            </ul>
        @endif
    </li>
@endforeach
@permission('edit-category')
<li class="header">Admin</li>
<li>
    <a class="add-cat" href="#" data-site_id="{{$site->id}}"
       data-href="{{ route('category.create', ['site_id' => $site->id]) }}">
        <span>{{ucfirst(trans('messages.ajouter'))}}</span>
    </a>
</li>
@endpermission

resources/views/site/single.blade.php
@extends('layouts.app')

@section('title', $site->name)

@section('content')
    <div class="row site-stats">
        @foreach($site->stats as $stat)
            <?php $score = null;
            $cats = [str_slug($stat->category->name).'-'.$stat->category->id];
            if ($stat->category->parent) {
                $cats[] = str_slug($stat->category->parent->name).'-'.$stat->category->parent->id;
            }
            ?>
            @if(!$stat->users->isEmpty())
                <?php $score = $stat->users->first()->pivot->score; ?>
            @endif
            <div class="col-xs-12 col-sm-6 col-md-4 box-stats"
                 data-groups='{{json_encode($cats)}}'>
                <div class="box box-solid box-primary">
                    <div class="box-header">
                        @permission('edit-category')
                        <span class="category">
                            <a href="#" data-href="{{ route('stat.edit', ['id' => $stat->id]) }}" class="edit-stat-cat"
                               data-stat_id="{{$stat->id}}">
                                <span>{{$stat->category->name}}</span>
                                <i class="fa fa-fw fa-pencil"></i>
                            </a>
                        </span>
                        @endpermission
                        <div class="stat">
                            <div class="stat-icon-container">
                                @if(!empty($stat->icon)){!! Html::image($stat->icon, $stat->name,['class'=>'stat-icon']) !!}@endif
                            </div>
                            <div class="box-title-container">
                                <h3 class="box-title{{strlen($stat->name) > 25 ? ' small' :'' }}">{{$stat->name}}</h3>
                            </div>
                            <div class="score-container">
                                <span class="label bg-aqua">{{$score}}</span>
                            </div>
                        </div>
                        @if($stat->description)<h4 class="desc">{{$stat->description}}</h4>@endif
                    </div>
                    <div class="box-body">
                        <ul class="list-unstyled">
                            @foreach($stat->achievements as $achievement)
                                <li {!! !$achievement->users->isEmpty() ? 'class="user-has"' : '' !!}>
                                    <span class="score">x{{$achievement->score}}</span>
                                    <span class="achievement-title">@include('components.achievement')</span>
                                    <span class="npoints">+{{$achievement->present()->points}}</span>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection